apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJjM0J5YjJkbmFUcG5hSEJmVUV4cVFVZEJiV0ZwVlhFMFJ6bGplWEJLUXpGWFJGbHVkbEkzTlRaUE5HTmhUVEJWIgogICAgfQogIH0KfQo=
